// File generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIXUzzjt5BE_pGmtIw2Dw2ZU6kjevkOM',
    appId: '1:365868224840:web:aed6e62c139bc9dfd1237d',
    messagingSenderId: '365868224840',
    projectId: 'wae-679cc',
    authDomain: 'wae-679cc.firebaseapp.com',
    storageBucket: 'wae-679cc.firebasestorage.app',
    measurementId: 'G-TWZYD3Y5TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2XHEXVOQrvHd4FNhjWbB03POOR02xH0',
    appId: '1:365868224840:android:d7cb928580da7619d1237d',
    messagingSenderId: '365868224840',
    projectId: 'wae-679cc',
    authDomain: 'wae-679cc.firebaseapp.com',
    storageBucket: 'wae-679cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYa6Ih2PcOSjafu0Yenk0lQvxiWXb5eKQ',
    appId: '1:365868224840:ios:a67389212f57d739d1237d',
    messagingSenderId: '365868224840',
    projectId: 'wae-679cc',
    authDomain: 'wae-679cc.firebaseapp.com',
    storageBucket: 'wae-679cc.firebasestorage.app',
    iosBundleId: 'com.example.deliveryUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYa6Ih2PcOSjafu0Yenk0lQvxiWXb5eKQ',
    appId: '1:365868224840:macos:a67389212f57d739d1237d',
    messagingSenderId: '365868224840',
    projectId: 'wae-679cc',
    authDomain: 'wae-679cc.firebaseapp.com',
    storageBucket: 'wae-679cc.firebasestorage.app',
    iosBundleId: 'com.example.deliveryUserApp',
  );
}

